package org.bubblecloud.zigbee.v3.zcl.clusters.iaszone;

import org.bubblecloud.zigbee.v3.zcl.ZclCommandMessage;
import org.bubblecloud.zigbee.v3.zcl.ZclCommand;
import org.bubblecloud.zigbee.v3.zcl.protocol.ZclCommandType;
import org.bubblecloud.zigbee.v3.zcl.protocol.ZclFieldType;


/**
 *  Zone Enroll Response value object class.
 * 
 * 
 * Cluster: IAS Zone
 * The IAS Zone cluster defines an interface to the functionality of an IAS security
 * zone device. IAS Zone supports up to two alarm types per zone, low battery
 * reports and supervision of the IAS network.
 * 
 * Code is autogenerated. Modifications may be overwritten!
 */
public class ZoneEnrollResponse extends ZclCommand {
    /**
     * Enroll response code command message field.
     */
    private Integer enrollResponseCode;
    /**
     * Zone ID command message field.
     */
    private Integer zoneId;

    /**
     * Default constructor setting the command type field.
     */
    public ZoneEnrollResponse() {
        setType(ZclCommandType.ZONE_ENROLL_RESPONSE);
    }

    /**
     * Constructor copying field values from command message.
     * @param message the command message
     */
    public ZoneEnrollResponse(final ZclCommandMessage message) {
        super(message);
        this.enrollResponseCode = (Integer) message.getFields().get(ZclFieldType.ZONE_ENROLL_RESPONSE_ENROLL_RESPONSE_CODE);
        this.zoneId = (Integer) message.getFields().get(ZclFieldType.ZONE_ENROLL_RESPONSE_ZONE_ID);
    }

    @Override
    public ZclCommandMessage toCommandMessage() {
        final ZclCommandMessage message = super.toCommandMessage();
        message.getFields().put(ZclFieldType.ZONE_ENROLL_RESPONSE_ENROLL_RESPONSE_CODE,enrollResponseCode);
        message.getFields().put(ZclFieldType.ZONE_ENROLL_RESPONSE_ZONE_ID,zoneId);
        return message;
    }

    /**
     * Gets Enroll response code.
     * @return the Enroll response code
     */
    public Integer getEnrollResponseCode() {
        return enrollResponseCode;
    }

    /**
     * Sets Enroll response code.
     * @param enrollResponseCode the Enroll response code
     */
    public void setEnrollResponseCode(final Integer enrollResponseCode) {
        this.enrollResponseCode = enrollResponseCode;
    }

    /**
     * Gets Zone ID.
     * @return the Zone ID
     */
    public Integer getZoneId() {
        return zoneId;
    }

    /**
     * Sets Zone ID.
     * @param zoneId the Zone ID
     */
    public void setZoneId(final Integer zoneId) {
        this.zoneId = zoneId;
    }

    @Override
    public String toString() {
        final StringBuilder builder = new StringBuilder();
        builder.append(super.toString());
        builder.append(", ");
        builder.append("enrollResponseCode");
        builder.append('=');
        builder.append(enrollResponseCode);
        builder.append(", ");
        builder.append("zoneId");
        builder.append('=');
        builder.append(zoneId);
        return builder.toString();
    }

}
