package org.bubblecloud.zigbee.network.zcl.protocol;

public enum ZclDataType {
    CHARACTER_STRING,
    CLUSTER_ID,
    IEEE_ADDRESS,
    N_X_EXTENSION_FIELD_SET,
    N_X_NEIGHBORS_INFORMATION,
    N_X_UNSIGNED_16_BIT_INTEGE,
    N_X_UNSIGNED_8_BIT_INTEGER,
    SIGNED_16_BIT_INTEGER,
    SIGNED_8_BIT_INTEGER,
    UNSIGNED_16_BIT_INTEGER,
    UNSIGNED_32_BIT_INTEGER,
    UNSIGNED_8_BIT_INTEGER,
    _16_BIT_ENUMERATION,
    _8_BIT_BITMAP,
    _8_BIT_DATA,
    _8_BIT_ENUMERATION
}
