package org.bubblecloud.zigbee.v3.zcl.clusters.colorcontrol;

import org.bubblecloud.zigbee.v3.zcl.ZclCommandMessage;
import org.bubblecloud.zigbee.v3.zcl.ZclCommand;
import org.bubblecloud.zigbee.v3.zcl.protocol.ZclCommandType;
import org.bubblecloud.zigbee.v3.zcl.protocol.ZclFieldType;


/**
 * Move Color Command value object class.
 * 
 * 
 * Cluster: Color control
 * This cluster provides an interface for changing the color of a light. Color is
 * specified according to the Commission Internationale de l'Éclairage (CIE)
 * specification CIE 1931 Color Space, [B4]. Color control is carried out in terms of
 * x,y values, as defined by this specification.
 * 
 * Code is autogenerated. Modifications may be overwritten!
 */
public class MoveColorCommand extends ZclCommand {
    /**
     * RateX command message field.
     */
    private Integer rateX;
    /**
     * RateY command message field.
     */
    private Integer rateY;

    /**
     * Default constructor setting the command type field.
     */
    public MoveColorCommand() {
        setType(ZclCommandType.MOVE_COLOR_COMMAND);
    }

    /**
     * Constructor copying field values from command message.
     * @param message the command message
     */
    public MoveColorCommand(final ZclCommandMessage message) {
        super(message);
        this.rateX = (Integer) message.getFields().get(ZclFieldType.MOVE_COLOR_COMMAND_RATEX);
        this.rateY = (Integer) message.getFields().get(ZclFieldType.MOVE_COLOR_COMMAND_RATEY);
    }

    @Override
    public ZclCommandMessage toCommandMessage() {
        final ZclCommandMessage message = super.toCommandMessage();
        message.getFields().put(ZclFieldType.MOVE_COLOR_COMMAND_RATEX,rateX);
        message.getFields().put(ZclFieldType.MOVE_COLOR_COMMAND_RATEY,rateY);
        return message;
    }

    /**
     * Gets RateX.
     * @return the RateX
     */
    public Integer getRateX() {
        return rateX;
    }

    /**
     * Sets RateX.
     * @param rateX the RateX
     */
    public void setRateX(final Integer rateX) {
        this.rateX = rateX;
    }

    /**
     * Gets RateY.
     * @return the RateY
     */
    public Integer getRateY() {
        return rateY;
    }

    /**
     * Sets RateY.
     * @param rateY the RateY
     */
    public void setRateY(final Integer rateY) {
        this.rateY = rateY;
    }

    @Override
    public String toString() {
        final StringBuilder builder = new StringBuilder();
        builder.append(super.toString());
        builder.append(", ");
        builder.append("rateX");
        builder.append('=');
        builder.append(rateX);
        builder.append(", ");
        builder.append("rateY");
        builder.append('=');
        builder.append(rateY);
        return builder.toString();
    }

}
