package org.bubblecloud.zigbee.v3.zcl.clusters.colorcontrol;

import org.bubblecloud.zigbee.v3.zcl.ZclCommandMessage;
import org.bubblecloud.zigbee.v3.zcl.ZclCommand;
import org.bubblecloud.zigbee.v3.zcl.protocol.ZclCommandType;
import org.bubblecloud.zigbee.v3.zcl.protocol.ZclFieldType;


/**
 * Step Hue Command value object class.
 * 
 * 
 * Cluster: Color control
 * This cluster provides an interface for changing the color of a light. Color is
 * specified according to the Commission Internationale de l'Éclairage (CIE)
 * specification CIE 1931 Color Space, [B4]. Color control is carried out in terms of
 * x,y values, as defined by this specification.
 * 
 * Code is autogenerated. Modifications may be overwritten!
 */
public class StepHueCommand extends ZclCommand {
    /**
     * Step mode command message field.
     */
    private Integer stepMode;
    /**
     * Step size command message field.
     */
    private Integer stepSize;
    /**
     * Transition time command message field.
     */
    private Integer transitionTime;

    /**
     * Default constructor setting the command type field.
     */
    public StepHueCommand() {
        setType(ZclCommandType.STEP_HUE_COMMAND);
    }

    /**
     * Constructor copying field values from command message.
     * @param message the command message
     */
    public StepHueCommand(final ZclCommandMessage message) {
        super(message);
        this.stepMode = (Integer) message.getFields().get(ZclFieldType.STEP_HUE_COMMAND_STEP_MODE);
        this.stepSize = (Integer) message.getFields().get(ZclFieldType.STEP_HUE_COMMAND_STEP_SIZE);
        this.transitionTime = (Integer) message.getFields().get(ZclFieldType.STEP_HUE_COMMAND_TRANSITION_TIME);
    }

    @Override
    public ZclCommandMessage toCommandMessage() {
        final ZclCommandMessage message = super.toCommandMessage();
        message.getFields().put(ZclFieldType.STEP_HUE_COMMAND_STEP_MODE,stepMode);
        message.getFields().put(ZclFieldType.STEP_HUE_COMMAND_STEP_SIZE,stepSize);
        message.getFields().put(ZclFieldType.STEP_HUE_COMMAND_TRANSITION_TIME,transitionTime);
        return message;
    }

    /**
     * Gets Step mode.
     * @return the Step mode
     */
    public Integer getStepMode() {
        return stepMode;
    }

    /**
     * Sets Step mode.
     * @param stepMode the Step mode
     */
    public void setStepMode(final Integer stepMode) {
        this.stepMode = stepMode;
    }

    /**
     * Gets Step size.
     * @return the Step size
     */
    public Integer getStepSize() {
        return stepSize;
    }

    /**
     * Sets Step size.
     * @param stepSize the Step size
     */
    public void setStepSize(final Integer stepSize) {
        this.stepSize = stepSize;
    }

    /**
     * Gets Transition time.
     * @return the Transition time
     */
    public Integer getTransitionTime() {
        return transitionTime;
    }

    /**
     * Sets Transition time.
     * @param transitionTime the Transition time
     */
    public void setTransitionTime(final Integer transitionTime) {
        this.transitionTime = transitionTime;
    }

    @Override
    public String toString() {
        final StringBuilder builder = new StringBuilder();
        builder.append(super.toString());
        builder.append(", ");
        builder.append("stepMode");
        builder.append('=');
        builder.append(stepMode);
        builder.append(", ");
        builder.append("stepSize");
        builder.append('=');
        builder.append(stepSize);
        builder.append(", ");
        builder.append("transitionTime");
        builder.append('=');
        builder.append(transitionTime);
        return builder.toString();
    }

}
