package org.bubblecloud.zigbee.v3.zcl.clusters.iasace;

import org.bubblecloud.zigbee.v3.zcl.ZclCommandMessage;
import org.bubblecloud.zigbee.v3.zcl.ZclCommand;
import org.bubblecloud.zigbee.v3.zcl.protocol.ZclCommandType;
import org.bubblecloud.zigbee.v3.zcl.protocol.ZclFieldType;


/**
 *  Arm Response value object class.
 * 
 * 
 * Cluster: IAS ACE
 * The IAS ACE cluster defines an interface to the functionality of any Ancillary
 * Control Equipment of the IAS system. Using this cluster, a ZigBee enabled ACE
 * device can access a IAS CIE device and manipulate the IAS system, on behalf of a
 * level-2 user.
 * 
 * Code is autogenerated. Modifications may be overwritten!
 */
public class ArmResponse extends ZclCommand {
    /**
     * Arm Notification command message field.
     */
    private Integer armNotification;

    /**
     * Default constructor setting the command type field.
     */
    public ArmResponse() {
        setType(ZclCommandType.ARM_RESPONSE);
    }

    /**
     * Constructor copying field values from command message.
     * @param message the command message
     */
    public ArmResponse(final ZclCommandMessage message) {
        super(message);
        this.armNotification = (Integer) message.getFields().get(ZclFieldType.ARM_RESPONSE_ARM_NOTIFICATION);
    }

    @Override
    public ZclCommandMessage toCommandMessage() {
        final ZclCommandMessage message = super.toCommandMessage();
        message.getFields().put(ZclFieldType.ARM_RESPONSE_ARM_NOTIFICATION,armNotification);
        return message;
    }

    /**
     * Gets Arm Notification.
     * @return the Arm Notification
     */
    public Integer getArmNotification() {
        return armNotification;
    }

    /**
     * Sets Arm Notification.
     * @param armNotification the Arm Notification
     */
    public void setArmNotification(final Integer armNotification) {
        this.armNotification = armNotification;
    }

    @Override
    public String toString() {
        final StringBuilder builder = new StringBuilder();
        builder.append(super.toString());
        builder.append(", ");
        builder.append("armNotification");
        builder.append('=');
        builder.append(armNotification);
        return builder.toString();
    }

}
