package org.bubblecloud.zigbee.v3.zcl.clusters.onoff;

import org.bubblecloud.zigbee.v3.zcl.ZclCommandMessage;
import org.bubblecloud.zigbee.v3.zcl.ZclCommand;
import org.bubblecloud.zigbee.v3.zcl.protocol.ZclCommandType;


/**
 * Toggle Command value object class.
 * 
 * 
 * Cluster: On/Off
 * Attributes and commands for switching devices between ‘On’ and ‘Off’ states.
 * 
 * Code is autogenerated. Modifications may be overwritten!
 */
public class ToggleCommand extends ZclCommand {

    /**
     * Default constructor setting the command type field.
     */
    public ToggleCommand() {
        setType(ZclCommandType.TOGGLE_COMMAND);
    }

    /**
     * Constructor copying field values from command message.
     * @param message the command message
     */
    public ToggleCommand(final ZclCommandMessage message) {
        super(message);
    }

    @Override
    public ZclCommandMessage toCommandMessage() {
        final ZclCommandMessage message = super.toCommandMessage();
        return message;
    }

    @Override
    public String toString() {
        final StringBuilder builder = new StringBuilder();
        builder.append(super.toString());
        return builder.toString();
    }

}
