package org.bubblecloud.zigbee.v3.zcl.protocol;

import org.bubblecloud.zigbee.v3.zcl.ZclUtil;

/**
 * Code generated command type registrar class.
 */
public class ZclCommandTypeRegistrar {
    /**
     * Register command types.
     */
    public static void register() {
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.RESET_TO_FACTORY_DEFAULTS_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.basic.
            ResetToFactoryDefaultsCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.IDENTIFY_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.identify.
            IdentifyCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.IDENTIFY_QUERY_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.identify.
            IdentifyQueryCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.IDENTIFY_QUERY_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.identify.
            IdentifyQueryResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.ADD_GROUP_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.groups.
            AddGroupCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.VIEW_GROUP_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.groups.
            ViewGroupCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.GET_GROUP_MEMBERSHIP_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.groups.
            GetGroupMembershipCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.REMOVE_GROUP_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.groups.
            RemoveGroupCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.REMOVE_ALL_GROUPS_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.groups.
            RemoveAllGroupsCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.ADD_GROUP_IF_IDENTIFYING_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.groups.
            AddGroupIfIdentifyingCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.ADD_GROUP_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.groups.
            AddGroupResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.VIEW_GROUP_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.groups.
            ViewGroupResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.GET_GROUP_MEMBERSHIP_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.groups.
            GetGroupMembershipResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.REMOVE_GROUP_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.groups.
            RemoveGroupResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.ADD_SCENE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.scenes.
            AddSceneCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.VIEW_SCENE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.scenes.
            ViewSceneCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.REMOVE_SCENE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.scenes.
            RemoveSceneCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.REMOVE_ALL_SCENES_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.scenes.
            RemoveAllScenesCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.STORE_SCENE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.scenes.
            StoreSceneCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.RECALL_SCENE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.scenes.
            RecallSceneCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.GET_SCENE_MEMBERSHIP_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.scenes.
            GetSceneMembershipCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.ADD_SCENE_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.scenes.
            AddSceneResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.VIEW_SCENE_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.scenes.
            ViewSceneResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.REMOVE_SCENE_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.scenes.
            RemoveSceneResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.REMOVE_ALL_SCENES_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.scenes.
            RemoveAllScenesResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.STORE_SCENE_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.scenes.
            StoreSceneResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.GET_SCENE_MEMBERSHIP_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.scenes.
            GetSceneMembershipResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.OFF_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.on.off.
            OffCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.ON_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.on.off.
            OnCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.TOGGLE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.on.off.
            ToggleCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.MOVE_TO_LEVEL_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.level.control.
            MoveToLevelCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.MOVE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.level.control.
            MoveCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.STEP_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.level.control.
            StepCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.STOP_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.level.control.
            StopCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.MOVE_TO_LEVEL__WITH_ON_OFF__COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.level.control.
            MoveToLevelWithOnOffCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.MOVE__WITH_ON_OFF__COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.level.control.
            MoveWithOnOffCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.STEP__WITH_ON_OFF__COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.level.control.
            StepWithOnOffCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.STOP_2_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.level.control.
            Stop2Command.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.RESET_ALARM_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.alarms.
            ResetAlarmCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.RESET_ALL_ALARMS_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.alarms.
            ResetAllAlarmsCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.GET_ALARM_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.alarms.
            GetAlarmCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.RESET_ALARM_LOG_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.alarms.
            ResetAlarmLogCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.ALARM_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.alarms.
            AlarmCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.GET_ALARM_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.alarms.
            GetAlarmResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.SET_ABSOLUTE_LOCATION_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.rssi.location.
            SetAbsoluteLocationCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.SET_DEVICE_CONFIGURATION_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.rssi.location.
            SetDeviceConfigurationCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.GET_DEVICE_CONFIGURATION_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.rssi.location.
            GetDeviceConfigurationCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.GET_LOCATION_DATA_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.rssi.location.
            GetLocationDataCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.RSSI_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.rssi.location.
            RssiResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.SEND_PINGS_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.rssi.location.
            SendPingsCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.ANCHOR_NODE_ANNOUNCE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.rssi.location.
            AnchorNodeAnnounceCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.DEVICE_CONFIGURATION_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.rssi.location.
            DeviceConfigurationResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.LOCATION_DATA_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.rssi.location.
            LocationDataResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.LOCATION_DATA_NOTIFICATION_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.rssi.location.
            LocationDataNotificationCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.COMPACT_LOCATION_DATA_NOTIFICATION_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.rssi.location.
            CompactLocationDataNotificationCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.RSSI_PING_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.rssi.location.
            RssiPingCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.RSSI_REQUEST_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.rssi.location.
            RssiRequestCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.REPORT_RSSI_MEASUREMENTS_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.rssi.location.
            ReportRssiMeasurementsCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.REQUEST_OWN_LOCATION_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.rssi.location.
            RequestOwnLocationCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.RESTART_DEVICE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.commissioning.
            RestartDeviceCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.SAVE_STARTUP_PARAMETERS_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.commissioning.
            SaveStartupParametersCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.RESTORE_STARTUP_PARAMETERS_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.commissioning.
            RestoreStartupParametersCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.RESET_STARTUP_PARAMETERS_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.commissioning.
            ResetStartupParametersCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.RESTART_DEVICE_RESPONSE_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.commissioning.
            RestartDeviceResponseResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.SAVE_STARTUP_PARAMETERS_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.commissioning.
            SaveStartupParametersResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.RESTORE_STARTUP_PARAMETERS_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.commissioning.
            RestoreStartupParametersResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.RESET_STARTUP_PARAMETERS_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.commissioning.
            ResetStartupParametersResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.LOCK_DOOR_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.door.lock.
            LockDoorCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.UNLOCK_DOOR_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.door.lock.
            UnlockDoorCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.LOCK_DOOR_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.door.lock.
            LockDoorResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.UNLOCK_DOOR_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.door.lock.
            UnlockDoorResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.SETPOINT_RAISE_LOWER_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.thermostat.
            SetpointRaiseLowerCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.MOVE_TO_HUE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.color.control.
            MoveToHueCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.MOVE_HUE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.color.control.
            MoveHueCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.STEP_HUE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.color.control.
            StepHueCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.MOVE_TO_SATURATION_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.color.control.
            MoveToSaturationCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.MOVE_SATURATION_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.color.control.
            MoveSaturationCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.STEP_SATURATION_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.color.control.
            StepSaturationCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.MOVE_TO_HUE_AND_SATURATION_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.color.control.
            MoveToHueAndSaturationCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.MOVE_TO_COLOR_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.color.control.
            MoveToColorCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.MOVE_COLOR_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.color.control.
            MoveColorCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.STEP_COLOR_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.color.control.
            StepColorCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.MOVE_TO_COLOR_TEMPERATURE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.color.control.
            MoveToColorTemperatureCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.ZONE_ENROLL_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.ias.zone.
            ZoneEnrollResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.ZONE_STATUS_CHANGE_NOTIFICATION_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.ias.zone.
            ZoneStatusChangeNotificationCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.ZONE_ENROLL_REQUEST_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.ias.zone.
            ZoneEnrollRequestCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.ARM_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.ias.ace.
            ArmCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.BYPASS_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.ias.ace.
            BypassCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.EMERGENCY_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.ias.ace.
            EmergencyCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.FIRE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.ias.ace.
            FireCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.PANIC_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.ias.ace.
            PanicCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.GET_ZONE_ID_MAP_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.ias.ace.
            GetZoneIdMapCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.GET_ZONE_INFORMATION_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.ias.ace.
            GetZoneInformationCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.ARM_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.ias.ace.
            ArmResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.GET_ZONE_ID_MAP_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.ias.ace.
            GetZoneIdMapResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.GET_ZONE_INFORMATION_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.ias.ace.
            GetZoneInformationResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.START_WARNING_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.ias.wd.
            StartWarningCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.SQUAWK_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.ias.wd.
            SquawkCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.READ_ATTRIBUTES_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.general.
            ReadAttributesCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.READ_ATTRIBUTES_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.general.
            ReadAttributesResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.WRITE_ATTRIBUTES_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.general.
            WriteAttributesCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.WRITE_ATTRIBUTES_UNDIVIDED_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.general.
            WriteAttributesUndividedCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.WRITE_ATTRIBUTES_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.general.
            WriteAttributesResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.WRITE_ATTRIBUTES_NO_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.general.
            WriteAttributesNoResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.CONFIGURE_REPORTING_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.general.
            ConfigureReportingCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.CONFIGURE_REPORTING_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.general.
            ConfigureReportingResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.READ_REPORTING_CONFIGURATION_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.general.
            ReadReportingConfigurationCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.READ_REPORTING_CONFIGURATION_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.general.
            ReadReportingConfigurationResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.REPORT_ATTRIBUTES_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.general.
            ReportAttributesCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.DEFAULT_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.general.
            DefaultResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.DISCOVER_ATTRIBUTES_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.general.
            DiscoverAttributesCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.DISCOVER_ATTRIBUTES_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.general.
            DiscoverAttributesResponseCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.READ_ATTRIBUTES_STRUCTURED_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.general.
            ReadAttributesStructuredCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.WRITE_ATTRIBUTES_STRUCTURED_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.general.
            WriteAttributesStructuredCommand.class);
        ZclUtil.registerCommandTypeClassMapping(ZclCommandType.WRITE_ATTRIBUTES_STRUCTURED_RESPONSE_COMMAND,
            org.bubblecloud.zigbee.v3.zcl.protocol.command.general.
            WriteAttributesStructuredResponseCommand.class);
    }
}
