package org.bubblecloud.zigbee.v3.zcl.clusters;

import java.util.concurrent.Future;
import org.bubblecloud.zigbee.v3.CommandResult;
import org.bubblecloud.zigbee.v3.ZigBeeApi;
import org.bubblecloud.zigbee.v3.ZigBeeDevice;
import org.bubblecloud.zigbee.v3.zcl.ZclCluster;
import org.bubblecloud.zigbee.v3.zcl.clusters.basic.ResetToFactoryDefaultsCommand;
import org.bubblecloud.zigbee.v3.zcl.protocol.ZclDataType;

/**
 * <b>Basic</b> cluster implementation (<i>Cluster ID 0x0000</i>).
 * This code is autogenerated. Modifications may be overwritten!
 */
public class ZclBasicCluster extends ZclCluster {
    // Cluster ID
    private static final int CLUSTER_ID = 0x0000;

    // Attribute constants
    private final int ATTR_ZCLVERSION = 0x0000;
    private final int ATTR_APPLICATIONVERSION = 0x0001;
    private final int ATTR_STACKVERSION = 0x0002;
    private final int ATTR_HWVERSION = 0x0003;
    private final int ATTR_MANUFACTURERNAME = 0x0004;
    private final int ATTR_MODELIDENTIFIER = 0x0005;
    private final int ATTR_DATECODE = 0x0006;
    private final int ATTR_POWERSOURCE = 0x0007;
    private final int ATTR_LOCATIONDESCRIPTION = 0x0010;
    private final int ATTR_PHYSICALENVIRONMENT = 0x0011;
    private final int ATTR_DEVICEENABLED = 0x0012;
    private final int ATTR_ALARMMASK = 0x0013;
    private final int ATTR_DISABLELOCALCONFIG = 0x0014;

    /**
     * Default constructor.
     */
    public ZclBasicCluster(final ZigBeeApi zigbeeApi, final ZigBeeDevice zigbeeDevice) {
        super(zigbeeApi, zigbeeDevice, CLUSTER_ID);
    }



    /**
     * Get the <i>ZCLVersion</i> attribute
     * <p>
     * The ZCLVersion attribute is 8 bits in length and specifies the version number of
     * the ZigBee Cluster Library that all clusters on this endpoint conform to.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getZclVersion() {
        return read(ATTR_ZCLVERSION);
    }


    /**
     * Get the <i>ApplicationVersion</i> attribute
     * <p>
     * <br>
     * The ApplicationVersion attribute is 8 bits in length and specifies the version
     * number of the application software contained in the device. The usage of this
     * attribute is manufacturer dependent.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getApplicationVersion() {
        return read(ATTR_APPLICATIONVERSION);
    }


    /**
     * Get the <i>StackVersion</i> attribute
     * <p>
     * <br>
     * The StackVersion attribute is 8 bits in length and specifies the version number
     * of the implementation of the ZigBee stack contained in the device. The usage of
     * this attribute is manufacturer dependent.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getStackVersion() {
        return read(ATTR_STACKVERSION);
    }


    /**
     * Get the <i>HWVersion</i> attribute
     * <p>
     * <br>
     * The HWVersion attribute is 8 bits in length and specifies the version number of
     * the hardware of the device. The usage of this attribute is manufacturer dependent.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getHwVersion() {
        return read(ATTR_HWVERSION);
    }


    /**
     * Get the <i>ManufacturerName</i> attribute
     * <p>
     * <br>
     * The ManufacturerName attribute is a maximum of 32 bytes in length and specifies
     * the name of the manufacturer as a ZigBee character string.
     * </p>
     * The attribute is of type {@link String}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getManufacturerName() {
        return read(ATTR_MANUFACTURERNAME);
    }


    /**
     * Get the <i>ModelIdentifier</i> attribute
     * <p>
     * <br>
     * The ModelIdentifier attribute is a maximum of 32 bytes in length and specifies the
     * model number (or other identifier) assigned by the manufacturer as a ZigBee character string.
     * </p>
     * The attribute is of type {@link String}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getModelIdentifier() {
        return read(ATTR_MODELIDENTIFIER);
    }


    /**
     * Get the <i>DateCode</i> attribute
     * <p>
     * <br>
     * The DateCode attribute is a ZigBee character string with a maximum length of 16 bytes.
     * The first 8 characters specify the date of manufacturer of the device in international
     * date notation according to ISO 8601, i.e. YYYYMMDD, e.g.
     * 20060814.
     * </p>
     * The attribute is of type {@link String}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getDateCode() {
        return read(ATTR_DATECODE);
    }


    /**
     * Get the <i>PowerSource</i> attribute
     * <p>
     * <br>
     * The PowerSource attribute is 8 bits in length and specifies the source(s) of power
     * available to the device. Bits b0–b6 of this attribute represent the primary power
     * source of the device and bit b7 indicates whether the device has a secondary power
     * source in the form of a battery backup.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getPowerSource() {
        return read(ATTR_POWERSOURCE);
    }


    /**
     * Set the <i>LocationDescription</i> attribute
     * <p>
     * <br>
     * The LocationDescription attribute is a maximum of 16 bytes in length and describes
     * the physical location of the device as a ZigBee character string.
     * </p>
     * The attribute is of type {@link String}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @param locationDescription the {@link String} attribute value to be set
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> setLocationDescription(final Object value) {
        return write(ATTR_LOCATIONDESCRIPTION, ZclDataType.CHARACTER_STRING, value);
    }


    /**
     * Get the <i>LocationDescription</i> attribute
     * <p>
     * <br>
     * The LocationDescription attribute is a maximum of 16 bytes in length and describes
     * the physical location of the device as a ZigBee character string.
     * </p>
     * The attribute is of type {@link String}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getLocationDescription() {
        return read(ATTR_LOCATIONDESCRIPTION);
    }


    /**
     * Set the <i>PhysicalEnvironment</i> attribute
     * <p>
     * <br>
     * The PhysicalEnvironment attribute is 8 bits in length and specifies the type of
     * physical environment in which the device will operate.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @param physicalEnvironment the {@link Integer} attribute value to be set
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> setPhysicalEnvironment(final Object value) {
        return write(ATTR_PHYSICALENVIRONMENT, ZclDataType.ENUMERATION_8_BIT, value);
    }


    /**
     * Get the <i>PhysicalEnvironment</i> attribute
     * <p>
     * <br>
     * The PhysicalEnvironment attribute is 8 bits in length and specifies the type of
     * physical environment in which the device will operate.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getPhysicalEnvironment() {
        return read(ATTR_PHYSICALENVIRONMENT);
    }


    /**
     * Set the <i>DeviceEnabled</i> attribute
     * <p>
     * <br>
     * The DeviceEnabled attribute is a boolean and specifies whether the device is enabled
     * or disabled.
     * </p>
     * The attribute is of type {@link Boolean}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @param deviceEnabled the {@link Boolean} attribute value to be set
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> setDeviceEnabled(final Object value) {
        return write(ATTR_DEVICEENABLED, ZclDataType.BOOLEAN, value);
    }


    /**
     * Get the <i>DeviceEnabled</i> attribute
     * <p>
     * <br>
     * The DeviceEnabled attribute is a boolean and specifies whether the device is enabled
     * or disabled.
     * </p>
     * The attribute is of type {@link Boolean}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getDeviceEnabled() {
        return read(ATTR_DEVICEENABLED);
    }


    /**
     * Set the <i>AlarmMask</i> attribute
     * <p>
     * <br>
     * The AlarmMask attribute is 8 bits in length and specifies which of a number of general
     * alarms may be generated.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @param alarmMask the {@link Integer} attribute value to be set
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> setAlarmMask(final Object value) {
        return write(ATTR_ALARMMASK, ZclDataType.BITMAP_8_BIT, value);
    }


    /**
     * Get the <i>AlarmMask</i> attribute
     * <p>
     * <br>
     * The AlarmMask attribute is 8 bits in length and specifies which of a number of general
     * alarms may be generated.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getAlarmMask() {
        return read(ATTR_ALARMMASK);
    }


    /**
     * Set the <i>DisableLocalConfig</i> attribute
     * <p>
     * <br>
     * The DisableLocalConfig attribute allows a number of local device configuration
     * functions to be disabled.
     * <br>
     * The intention of this attribute is to allow disabling of any local configuration
     * user interface, for example to prevent reset or binding buttons being activated by
     * unauthorised persons in a public building.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @param disableLocalConfig the {@link Integer} attribute value to be set
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> setDisableLocalConfig(final Object value) {
        return write(ATTR_DISABLELOCALCONFIG, ZclDataType.BITMAP_8_BIT, value);
    }


    /**
     * Get the <i>DisableLocalConfig</i> attribute
     * <p>
     * <br>
     * The DisableLocalConfig attribute allows a number of local device configuration
     * functions to be disabled.
     * <br>
     * The intention of this attribute is to allow disabling of any local configuration
     * user interface, for example to prevent reset or binding buttons being activated by
     * unauthorised persons in a public building.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getDisableLocalConfig() {
        return read(ATTR_DISABLELOCALCONFIG);
    }


    /**
     * The Reset to Factory Defaults Command
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> resetToFactoryDefaultsCommand() {
        return send(new ResetToFactoryDefaultsCommand());
    }


    /**
     * Add a binding for this cluster to the local node
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> bind() {
        return bind();
    }

}
