package org.bubblecloud.zigbee.v3.zcl.clusters;

import java.util.concurrent.Future;
import org.bubblecloud.zigbee.v3.CommandResult;
import org.bubblecloud.zigbee.v3.ZigBeeApi;
import org.bubblecloud.zigbee.v3.ZigBeeDevice;
import org.bubblecloud.zigbee.v3.zcl.ZclCluster;

/**
 * <b>Flow measurement</b> cluster implementation (<i>Cluster ID 0x0404</i>).
 * This code is autogenerated. Modifications may be overwritten!
 */
public class ZclFlowMeasurementCluster extends ZclCluster {
    // Cluster ID
    private static final int CLUSTER_ID = 0x0404;

    // Attribute constants
    private final int ATTR_MEASUREDVALUE = 0x0000;
    private final int ATTR_MINMEASUREDVALUE = 0x0001;
    private final int ATTR_MAXMEASUREDVALUE = 0x0002;
    private final int ATTR_TOLERANCE = 0x0003;

    /**
     * Default constructor.
     */
    public ZclFlowMeasurementCluster(final ZigBeeApi zigbeeApi, final ZigBeeDevice zigbeeDevice) {
        super(zigbeeApi, zigbeeDevice, CLUSTER_ID);
    }



    /**
     * Get the <i>MeasuredValue</i> attribute
     * <p>
     * MeasuredValue represents the flow in m3/h as follows:-
     * <br>
     * MeasuredValue = 10 x Flow
     * <br>
     * Where 0 m3/h <= Flow <= 6,553.4 m3
     * <br>
     * /h, corresponding to a MeasuredValue in the
     * range 0 to 0xfffe.
     * <br>
     * The maximum resolution this format allows is 0.1 m3/h.
     * <br>
     * A MeasuredValue of 0xffff indicates that the pressure measurement is invalid.
     * <br>
     * MeasuredValue is updated continuously as new measurements are made.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getMeasuredValue() {
        return read(ATTR_MEASUREDVALUE);
    }


    /**
     * Get the <i>MinMeasuredValue</i> attribute
     * <p>
     * <br>
     * The MinMeasuredValue attribute indicates the minimum value of MeasuredValue
     * that can be measured. A value of 0xffff means this attribute is not defined
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getMinMeasuredValue() {
        return read(ATTR_MINMEASUREDVALUE);
    }


    /**
     * Get the <i>MaxMeasuredValue</i> attribute
     * <p>
     * <br>
     * The MaxMeasuredValue attribute indicates the maximum value of MeasuredValue
     * that can be measured. A value of 0xffff means this attribute is not defined.
     * <br>
     * MaxMeasuredValue shall be greater than MinMeasuredValue.
     * <br>
     * MinMeasuredValue and MaxMeasuredValue define the range of the sensor
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getMaxMeasuredValue() {
        return read(ATTR_MAXMEASUREDVALUE);
    }


    /**
     * Get the <i>Tolerance</i> attribute
     * <p>
     * <br>
     * The Tolerance attribute indicates the magnitude of the possible error that is
     * associated with MeasuredValue . The true value is located in the range
     * (MeasuredValue – Tolerance) to (MeasuredValue + Tolerance).
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getTolerance() {
        return read(ATTR_TOLERANCE);
    }

}
