package org.bubblecloud.zigbee.v3.zcl.clusters;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.Future;
import org.bubblecloud.zigbee.v3.CommandResult;
import org.bubblecloud.zigbee.v3.ZigBeeApi;
import org.bubblecloud.zigbee.v3.ZigBeeDevice;
import org.bubblecloud.zigbee.v3.zcl.ZclAttribute;
import org.bubblecloud.zigbee.v3.zcl.ZclCluster;
import org.bubblecloud.zigbee.v3.zcl.protocol.ZclDataType;

/**
 * <b>Illuminance measurement</b> cluster implementation (<i>Cluster ID 0x0400</i>).
 * <p>
 * The cluster provides an interface to illuminance measurement functionality,
 * including configuration and provision of notifications of illuminance
 * measurements.
 * </p>
 * This code is autogenerated. Modifications may be overwritten!
 */
public class ZclIlluminanceMeasurementCluster extends ZclCluster {
    // Cluster ID
    private static final int CLUSTER_ID = 0x0400;

    // Attribute constants
    private final int ATTR_MEASUREDVALUE = 0x0000;
    private final int ATTR_MINMEASUREDVALUE = 0x0001;
    private final int ATTR_MAXMEASUREDVALUE = 0x0002;
    private final int ATTR_TOLERANCE = 0x0003;
    private final int ATTR_LIGHTSENSORTYPE = 0x0004;

    // Attribute initialisation
    protected Map<Integer, ZclAttribute> initializeAttributes() {
        Map<Integer, ZclAttribute> attributeMap = new HashMap<Integer, ZclAttribute>(5);

        attributeMap.put(ATTR_MEASUREDVALUE, new ZclAttribute(0, ZclDataType.UNSIGNED_16_BIT_INTEGER, 
                true, true, false, true));
        attributeMap.put(ATTR_MINMEASUREDVALUE, new ZclAttribute(1, ZclDataType.UNSIGNED_16_BIT_INTEGER, 
                true, true, false, false));
        attributeMap.put(ATTR_MAXMEASUREDVALUE, new ZclAttribute(2, ZclDataType.UNSIGNED_16_BIT_INTEGER, 
                true, true, false, false));
        attributeMap.put(ATTR_TOLERANCE, new ZclAttribute(3, ZclDataType.UNSIGNED_16_BIT_INTEGER, 
                false, true, false, true));
        attributeMap.put(ATTR_LIGHTSENSORTYPE, new ZclAttribute(4, ZclDataType.ENUMERATION_8_BIT, 
                false, true, false, false));

        return attributeMap;
    }

    /**
     * Default constructor.
     */
    public ZclIlluminanceMeasurementCluster(final ZigBeeApi zigbeeApi, final ZigBeeDevice zigbeeDevice) {
        super(zigbeeApi, zigbeeDevice, CLUSTER_ID);
    }



    /**
     * Get the <i>MeasuredValue</i> attribute
     * <p>
     * MeasuredValue represents the Illuminance in Lux (symbol lx) as follows:-
     * <br>
     * MeasuredValue = 10,000 x log10 Illuminance + 1
     * <br>
     * Where 1 lx <= Illuminance <=3.576 Mlx, corresponding to a MeasuredValue in
     * the range 1 to 0xfffe.
     * <br>
     * The following special values of MeasuredValue apply.
     * <li>0x0000 indicates a value of Illuminance that is too low to be measured.</li>
     * <li>0xffff indicates that the Illuminance measurement is invalid.</li>
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getMeasuredValue() {
        return read(ATTR_MEASUREDVALUE);
    }


    /**
     * Configure reporting for the <i>MeasuredValue</i> attribute
     * <p>
     * MeasuredValue represents the Illuminance in Lux (symbol lx) as follows:-
     * <br>
     * MeasuredValue = 10,000 x log10 Illuminance + 1
     * <br>
     * Where 1 lx <= Illuminance <=3.576 Mlx, corresponding to a MeasuredValue in
     * the range 1 to 0xfffe.
     * <br>
     * The following special values of MeasuredValue apply.
     * <li>0x0000 indicates a value of Illuminance that is too low to be measured.</li>
     * <li>0xffff indicates that the Illuminance measurement is invalid.</li>
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @param minInterval {@link int} minimum reporting period
     * @param maxInterval {@link int} maximum reporting period
     * @param reportableChange {@link Object} delta required to trigger report
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> configMeasuredValueReporting(final int minInterval, final int maxInterval, final Object reportableChange) {
        return report(ATTR_MEASUREDVALUE, minInterval, maxInterval, reportableChange);
    }


    /**
     * Get the <i>MinMeasuredValue</i> attribute
     * <p>
     * <br>
     * The MinMeasuredValue attribute indicates the minimum value of MeasuredValue
     * that can be measured. A value of 0xffff indicates that this attribute is not defined.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getMinMeasuredValue() {
        return read(ATTR_MINMEASUREDVALUE);
    }


    /**
     * Get the <i>MaxMeasuredValue</i> attribute
     * <p>
     * <br>
     * The MaxMeasuredValue attribute indicates the maximum value of MeasuredValue
     * that can be measured. A value of 0xffff indicates that this attribute is not defined.
     * <br>
     * MaxMeasuredValue shall be greater than MinMeasuredValue.
     * <br>
     * MinMeasuredValue and MaxMeasuredValue define the range of the sensor.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getMaxMeasuredValue() {
        return read(ATTR_MAXMEASUREDVALUE);
    }


    /**
     * Get the <i>Tolerance</i> attribute
     * <p>
     * <br>
     * The Tolerance attribute indicates the magnitude of the possible error that is
     * associated with MeasuredValue . The true value is located in the range
     * (MeasuredValue – Tolerance) to (MeasuredValue + Tolerance).
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getTolerance() {
        return read(ATTR_TOLERANCE);
    }


    /**
     * Configure reporting for the <i>Tolerance</i> attribute
     * <p>
     * <br>
     * The Tolerance attribute indicates the magnitude of the possible error that is
     * associated with MeasuredValue . The true value is located in the range
     * (MeasuredValue – Tolerance) to (MeasuredValue + Tolerance).
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @param minInterval {@link int} minimum reporting period
     * @param maxInterval {@link int} maximum reporting period
     * @param reportableChange {@link Object} delta required to trigger report
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> configToleranceReporting(final int minInterval, final int maxInterval, final Object reportableChange) {
        return report(ATTR_TOLERANCE, minInterval, maxInterval, reportableChange);
    }


    /**
     * Get the <i>LightSensorType</i> attribute
     * <p>
     * <br>
     * The LightSensorType attribute specifies the electronic type of the light sensor.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getLightSensorType() {
        return read(ATTR_LIGHTSENSORTYPE);
    }


    /**
     * Add a binding for this cluster to the local node
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> bind() {
        return bind();
    }

}
