package org.bubblecloud.zigbee.v3.zcl.clusters;

import java.util.concurrent.Future;
import org.bubblecloud.zigbee.v3.CommandResult;
import org.bubblecloud.zigbee.v3.ZigBeeApi;
import org.bubblecloud.zigbee.v3.ZigBeeDevice;
import org.bubblecloud.zigbee.v3.zcl.ZclCluster;
import org.bubblecloud.zigbee.v3.zcl.clusters.iaszone.ZoneEnrollRequestCommand;
import org.bubblecloud.zigbee.v3.zcl.clusters.iaszone.ZoneEnrollResponse;
import org.bubblecloud.zigbee.v3.zcl.clusters.iaszone.ZoneStatusChangeNotificationCommand;

/**
 * <b>IAS Zone</b> cluster implementation (<i>Cluster ID 0x0500</i>).
 * <p>
 * The IAS Zone cluster defines an interface to the functionality of an IAS security
 * zone device. IAS Zone supports up to two alarm types per zone, low battery
 * reports and supervision of the IAS network.
 * </p>
 * This code is autogenerated. Modifications may be overwritten!
 */
public class ZclIasZoneCluster extends ZclCluster {
    // Cluster ID
    private static final int CLUSTER_ID = 0x0500;

    // Attribute constants
    private final int ATTR_ZONESTATE = 0x0000;
    private final int ATTR_ZONETYPE = 0x0001;
    private final int ATTR_ZONESTATUS = 0x0002;
    private final int ATTR_IAS_CIE_ADDRESS = 0x0010;

    /**
     * Default constructor.
     */
    public ZclIasZoneCluster(final ZigBeeApi zigbeeApi, final ZigBeeDevice zigbeeDevice) {
        super(zigbeeApi, zigbeeDevice, CLUSTER_ID);
    }



    /**
     * Get the <i>ZoneState</i> attribute
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getZoneState() {
        return read(ATTR_ZONESTATE);
    }


    /**
     * Get the <i>ZoneType</i> attribute
     * <p>
     * The Zone Type dictates the meaning of Alarm1 and Alarm2 bits of the ZoneStatus attribute
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getZoneType() {
        return read(ATTR_ZONETYPE);
    }


    /**
     * Get the <i>ZoneStatus</i> attribute
     * <p>
     * <br>
     * The ZoneStatus attribute is a bit map.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getZoneStatus() {
        return read(ATTR_ZONESTATUS);
    }


    /**
     * Set the <i>IAS_CIE_Address</i> attribute
     * <p>
     * <br>
     * The IAS_CIE_Address attribute specifies the address that commands generated by
     * the server shall be sent to. All commands received by the server must also come
     * from this address.
     * <br>
     * It is up to the zone's specific implementation to permit or deny change (write) of
     * this attribute at specific times. Also, it is up to the zone's specific implementation
     * to implement some auto-detect for the CIE (example: by requesting the ZigBee
     * cluster discovery service to locate a Zone Server cluster.) or require the
     * intervention of a CT in order to configure this attribute during installation.
     * </p>
     * The attribute is of type {@link Long}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @param ias_Cie_Address the {@link Long} attribute value to be set
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> setIas_Cie_Address(final Object value) {
        return write(ATTR_IAS_CIE_ADDRESS, value);
    }


    /**
     * Get the <i>IAS_CIE_Address</i> attribute
     * <p>
     * <br>
     * The IAS_CIE_Address attribute specifies the address that commands generated by
     * the server shall be sent to. All commands received by the server must also come
     * from this address.
     * <br>
     * It is up to the zone's specific implementation to permit or deny change (write) of
     * this attribute at specific times. Also, it is up to the zone's specific implementation
     * to implement some auto-detect for the CIE (example: by requesting the ZigBee
     * cluster discovery service to locate a Zone Server cluster.) or require the
     * intervention of a CT in order to configure this attribute during installation.
     * </p>
     * The attribute is of type {@link Long}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getIas_Cie_Address() {
        return read(ATTR_IAS_CIE_ADDRESS);
    }


    /**
     * The  Zone Enroll Response
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> zoneEnrollResponse() {
        return send(new ZoneEnrollResponse());
    }


    /**
     * The Zone Status Change Notification Command
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> zoneStatusChangeNotificationCommand() {
        return send(new ZoneStatusChangeNotificationCommand());
    }


    /**
     * The Zone Enroll Request Command
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> zoneEnrollRequestCommand() {
        return send(new ZoneEnrollRequestCommand());
    }

}
