package org.bubblecloud.zigbee.v3.zcl.clusters;

import java.util.concurrent.Future;
import org.bubblecloud.zigbee.v3.CommandResult;
import org.bubblecloud.zigbee.v3.ZigBeeApi;
import org.bubblecloud.zigbee.v3.ZigBeeDevice;
import org.bubblecloud.zigbee.v3.zcl.ZclCluster;

/**
 * <b>On/off Switch Configuration</b> cluster implementation (<i>Cluster ID 0x0007</i>).
 * <p>
 * Attributes and commands for configuring On/Off switching devices
 * </p>
 * This code is autogenerated. Modifications may be overwritten!
 */
public class ZclOnOffSwitchConfigurationCluster extends ZclCluster {
    // Cluster ID
    private static final int CLUSTER_ID = 0x0007;

    /**
     * Default constructor.
     */
    public ZclOnOffSwitchConfigurationCluster(final ZigBeeApi zigbeeApi, final ZigBeeDevice zigbeeDevice) {
        super(zigbeeApi, zigbeeDevice, CLUSTER_ID);
    }


}
