package org.bubblecloud.zigbee.v3.zcl.clusters;

import java.util.concurrent.Future;
import org.bubblecloud.zigbee.v3.CommandResult;
import org.bubblecloud.zigbee.v3.ZigBeeApi;
import org.bubblecloud.zigbee.v3.ZigBeeDevice;
import org.bubblecloud.zigbee.v3.zcl.ZclCluster;

/**
 * <b>Time</b> cluster implementation (<i>Cluster ID 0x000A</i>).
 * This code is autogenerated. Modifications may be overwritten!
 */
public class ZclTimeCluster extends ZclCluster {
    // Cluster ID
    private static final int CLUSTER_ID = 0x000A;

    // Attribute constants
    private final int ATTR_TIME = 0x0000;
    private final int ATTR_TIMESTATUS = 0x0001;
    private final int ATTR_TIMEZONE = 0x0002;
    private final int ATTR_DSTSTART = 0x0003;
    private final int ATTR_DSTEND = 0x0004;
    private final int ATTR_DSTSHIFT = 0x0005;
    private final int ATTR_STANDARDTIME = 0x0006;
    private final int ATTR_LOCALTIME = 0x0007;

    /**
     * Default constructor.
     */
    public ZclTimeCluster(final ZigBeeApi zigbeeApi, final ZigBeeDevice zigbeeDevice) {
        super(zigbeeApi, zigbeeDevice, CLUSTER_ID);
    }



    /**
     * Set the <i>Time</i> attribute
     * <p>
     * The Time attribute is 32-bits in length and holds the time value of a real time
     * clock. This attribute has data type UTCTime, but note that it may not actually be
     * synchronised to UTC - see discussion of the TimeStatus attribute below.
     * <br>
     * If the Master bit of the TimeStatus attribute has a value of 0, writing to this
     * attribute shall set the real time clock to the written value, otherwise it cannot be
     * written. The value 0xffffffff indicates an invalid time.
     * </p>
     * The attribute is of type {@link Calendar}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @param time the {@link Calendar} attribute value to be set
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> setTime(final Object value) {
        return write(ATTR_TIME, value);
    }


    /**
     * Get the <i>Time</i> attribute
     * <p>
     * The Time attribute is 32-bits in length and holds the time value of a real time
     * clock. This attribute has data type UTCTime, but note that it may not actually be
     * synchronised to UTC - see discussion of the TimeStatus attribute below.
     * <br>
     * If the Master bit of the TimeStatus attribute has a value of 0, writing to this
     * attribute shall set the real time clock to the written value, otherwise it cannot be
     * written. The value 0xffffffff indicates an invalid time.
     * </p>
     * The attribute is of type {@link Calendar}<br>
     * The implementation of this attribute by a device is MANDATORY
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getTime() {
        return read(ATTR_TIME);
    }


    /**
     * Set the <i>TimeStatus</i> attribute
     * <p>
     * <br>
     * The TimeStatus attribute holds a number of bit fields.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @param timeStatus the {@link Integer} attribute value to be set
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> setTimeStatus(final Object value) {
        return write(ATTR_TIMESTATUS, value);
    }


    /**
     * Get the <i>TimeStatus</i> attribute
     * <p>
     * <br>
     * The TimeStatus attribute holds a number of bit fields.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getTimeStatus() {
        return read(ATTR_TIMESTATUS);
    }


    /**
     * Set the <i>TimeZone</i> attribute
     * <p>
     * <br>
     * The TimeZone attribute indicates the local time zone, as a signed offset in seconds
     * from the Time attribute value. The value 0xffffffff indicates an invalid time zone.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @param timeZone the {@link Integer} attribute value to be set
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> setTimeZone(final Object value) {
        return write(ATTR_TIMEZONE, value);
    }


    /**
     * Get the <i>TimeZone</i> attribute
     * <p>
     * <br>
     * The TimeZone attribute indicates the local time zone, as a signed offset in seconds
     * from the Time attribute value. The value 0xffffffff indicates an invalid time zone.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getTimeZone() {
        return read(ATTR_TIMEZONE);
    }


    /**
     * Set the <i>DstStart</i> attribute
     * <p>
     * <br>
     * The DstStart attribute indicates the DST start time in seconds. The value 0xffffffff
     * indicates an invalid DST start time.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @param dstStart the {@link Integer} attribute value to be set
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> setDstStart(final Object value) {
        return write(ATTR_DSTSTART, value);
    }


    /**
     * Get the <i>DstStart</i> attribute
     * <p>
     * <br>
     * The DstStart attribute indicates the DST start time in seconds. The value 0xffffffff
     * indicates an invalid DST start time.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getDstStart() {
        return read(ATTR_DSTSTART);
    }


    /**
     * Set the <i>DstEnd</i> attribute
     * <p>
     * <br>
     * The DstEnd attribute indicates the DST end time in seconds. The value 0xffffffff
     * indicates an invalid DST end time.
     * <br>
     * Note that the three attributes DstStart, DstEnd and DstShift are optional, but if any
     * one of them is implemented the other two must also be implemented.
     * Note that this attribute should be set to a new value once every year.
     * <br>
     * Note that this attribute should be set to a new value once every year, and should be
     * written synchronously with the DstStart attribute.
     * <br>
     * The DstEnd attribute indicates the DST end time in seconds. The value 0xffffffff
     * indicates an invalid DST end time.
     * <br>
     * Note that this attribute should be set to a new value once every year, and should be
     * written synchronously with the DstStart attribute
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @param dstEnd the {@link Integer} attribute value to be set
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> setDstEnd(final Object value) {
        return write(ATTR_DSTEND, value);
    }


    /**
     * Get the <i>DstEnd</i> attribute
     * <p>
     * <br>
     * The DstEnd attribute indicates the DST end time in seconds. The value 0xffffffff
     * indicates an invalid DST end time.
     * <br>
     * Note that the three attributes DstStart, DstEnd and DstShift are optional, but if any
     * one of them is implemented the other two must also be implemented.
     * Note that this attribute should be set to a new value once every year.
     * <br>
     * Note that this attribute should be set to a new value once every year, and should be
     * written synchronously with the DstStart attribute.
     * <br>
     * The DstEnd attribute indicates the DST end time in seconds. The value 0xffffffff
     * indicates an invalid DST end time.
     * <br>
     * Note that this attribute should be set to a new value once every year, and should be
     * written synchronously with the DstStart attribute
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getDstEnd() {
        return read(ATTR_DSTEND);
    }


    /**
     * Set the <i>DstShift</i> attribute
     * <p>
     * <br>
     * The DstShift attribute represents a signed offset in seconds from the standard time,
     * to be applied between the times DstStart and DstEnd to calculate the Local Time.
     * The value 0xffffffff indicates an invalid DST shift.
     * <br>
     * The range of this attribute is +/- one day. Note that the actual range of DST values
     * employed by countries is much smaller than this, so the manufacturer has the
     * option to impose a smaller range.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @param dstShift the {@link Integer} attribute value to be set
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> setDstShift(final Object value) {
        return write(ATTR_DSTSHIFT, value);
    }


    /**
     * Get the <i>DstShift</i> attribute
     * <p>
     * <br>
     * The DstShift attribute represents a signed offset in seconds from the standard time,
     * to be applied between the times DstStart and DstEnd to calculate the Local Time.
     * The value 0xffffffff indicates an invalid DST shift.
     * <br>
     * The range of this attribute is +/- one day. Note that the actual range of DST values
     * employed by countries is much smaller than this, so the manufacturer has the
     * option to impose a smaller range.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getDstShift() {
        return read(ATTR_DSTSHIFT);
    }


    /**
     * Get the <i>StandardTime</i> attribute
     * <p>
     * <br>
     * A device may derive the time by reading the Time and TimeZone attributes
     * and adding them together. If implemented however, the optional StandardTime
     * attribute indicates this time directly. The value 0xffffffff indicates an invalid
     * Standard Time.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getStandardTime() {
        return read(ATTR_STANDARDTIME);
    }


    /**
     * Get the <i>LocalTime</i> attribute
     * <p>
     * <br>
     * A device may derive the time by reading the Time, TimeZone, DstStart, DstEnd
     * and DstShift attributes and performing the calculation. If implemented however,
     * the optional LocalTime attribute indicates this time directly. The value 0xffffffff
     * indicates an invalid Local Time.
     * </p>
     * The attribute is of type {@link Integer}<br>
     * The implementation of this attribute by a device is OPTIONAL
     *
     * @return the {@link Future<CommandResult>} command result future
     */
    public Future<CommandResult> getLocalTime() {
        return read(ATTR_LOCALTIME);
    }

}
