package org.bubblecloud.zigbee.v3.zcl.clusters.scenes;

import org.bubblecloud.zigbee.v3.zcl.ZclCommandMessage;
import org.bubblecloud.zigbee.v3.zcl.ZclCommand;
import org.bubblecloud.zigbee.v3.zcl.protocol.ZclCommandType;
import org.bubblecloud.zigbee.v3.zcl.protocol.ZclFieldType;
import org.bubblecloud.zigbee.v3.zcl.field.*;

import java.util.List;

/**
 *  Get Scene Membership Response value object class.
 * 
 * 
 * Cluster: Scenes
 * The scenes cluster provides attributes and commands for setting up and recalling
 * scenes. Each scene corresponds to a set of stored values of specified attributes for
 * one or more clusters on the same end point as the scenes cluster.
 * <br>
 * In most cases scenes are associated with a particular group ID. Scenes may also
 * exist without a group, in which case the value 0x0000 replaces the group ID. Note
 * that extra care is required in these cases to avoid a scene ID collision, and that
 * commands related to scenes without a group may only be unicast, i.e.: they may
 * not be multicast or broadcast.
 * 
 * Code is autogenerated. Modifications may be overwritten!
 */
public class GetSceneMembershipResponse extends ZclCommand {
    /**
     * Status command message field.
     */
    private Integer status;
    /**
     * Capacity command message field.
     */
    private Integer capacity;
    /**
     * Group ID command message field.
     */
    private Integer groupId;
    /**
     * Scene count command message field.
     */
    private Integer sceneCount;
    /**
     * Scene list command message field.
     */
    private List<Unsigned8BitInteger> sceneList;

    /**
     * Default constructor setting the command type field.
     */
    public GetSceneMembershipResponse() {
        setType(ZclCommandType.GET_SCENE_MEMBERSHIP_RESPONSE);
    }

    /**
     * Constructor copying field values from command message.
     * @param message the command message
     */
    public GetSceneMembershipResponse(final ZclCommandMessage message) {
        super(message);
        this.status = (Integer) message.getFields().get(ZclFieldType.GET_SCENE_MEMBERSHIP_RESPONSE_STATUS);
        this.capacity = (Integer) message.getFields().get(ZclFieldType.GET_SCENE_MEMBERSHIP_RESPONSE_CAPACITY);
        this.groupId = (Integer) message.getFields().get(ZclFieldType.GET_SCENE_MEMBERSHIP_RESPONSE_GROUP_ID);
        this.sceneCount = (Integer) message.getFields().get(ZclFieldType.GET_SCENE_MEMBERSHIP_RESPONSE_SCENE_COUNT);
        this.sceneList = (List<Unsigned8BitInteger>) message.getFields().get(ZclFieldType.GET_SCENE_MEMBERSHIP_RESPONSE_SCENE_LIST);
    }

    @Override
    public ZclCommandMessage toCommandMessage() {
        final ZclCommandMessage message = super.toCommandMessage();
        message.getFields().put(ZclFieldType.GET_SCENE_MEMBERSHIP_RESPONSE_STATUS,status);
        message.getFields().put(ZclFieldType.GET_SCENE_MEMBERSHIP_RESPONSE_CAPACITY,capacity);
        message.getFields().put(ZclFieldType.GET_SCENE_MEMBERSHIP_RESPONSE_GROUP_ID,groupId);
        message.getFields().put(ZclFieldType.GET_SCENE_MEMBERSHIP_RESPONSE_SCENE_COUNT,sceneCount);
        message.getFields().put(ZclFieldType.GET_SCENE_MEMBERSHIP_RESPONSE_SCENE_LIST,sceneList);
        return message;
    }

    /**
     * Gets Status.
     * @return the Status
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * Sets Status.
     * @param status the Status
     */
    public void setStatus(final Integer status) {
        this.status = status;
    }

    /**
     * Gets Capacity.
     * @return the Capacity
     */
    public Integer getCapacity() {
        return capacity;
    }

    /**
     * Sets Capacity.
     * @param capacity the Capacity
     */
    public void setCapacity(final Integer capacity) {
        this.capacity = capacity;
    }

    /**
     * Gets Group ID.
     * @return the Group ID
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * Sets Group ID.
     * @param groupId the Group ID
     */
    public void setGroupId(final Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * Gets Scene count.
     * @return the Scene count
     */
    public Integer getSceneCount() {
        return sceneCount;
    }

    /**
     * Sets Scene count.
     * @param sceneCount the Scene count
     */
    public void setSceneCount(final Integer sceneCount) {
        this.sceneCount = sceneCount;
    }

    /**
     * Gets Scene list.
     * @return the Scene list
     */
    public List<Unsigned8BitInteger> getSceneList() {
        return sceneList;
    }

    /**
     * Sets Scene list.
     * @param sceneList the Scene list
     */
    public void setSceneList(final List<Unsigned8BitInteger> sceneList) {
        this.sceneList = sceneList;
    }

    @Override
    public String toString() {
        final StringBuilder builder = new StringBuilder();
        builder.append(super.toString());
        builder.append(", ");
        builder.append("status");
        builder.append('=');
        builder.append(status);
        builder.append(", ");
        builder.append("capacity");
        builder.append('=');
        builder.append(capacity);
        builder.append(", ");
        builder.append("groupId");
        builder.append('=');
        builder.append(groupId);
        builder.append(", ");
        builder.append("sceneCount");
        builder.append('=');
        builder.append(sceneCount);
        builder.append(", ");
        builder.append("sceneList");
        builder.append('=');
        builder.append(sceneList);
        return builder.toString();
    }

}
