package org.bubblecloud.zigbee.v3.zcl.clusters.rssilocation;

import org.bubblecloud.zigbee.v3.zcl.ZclCommandMessage;
import org.bubblecloud.zigbee.v3.zcl.ZclCommand;
import org.bubblecloud.zigbee.v3.zcl.protocol.ZclCommandType;


/**
 * RSSI Request Command value object class.
 * 
 * 
 * Cluster: RSSI Location
 * 
 * Code is autogenerated. Modifications may be overwritten!
 */
public class RssiRequestCommand extends ZclCommand {

    /**
     * Default constructor setting the command type field.
     */
    public RssiRequestCommand() {
        setType(ZclCommandType.RSSI_REQUEST_COMMAND);
    }

    /**
     * Constructor copying field values from command message.
     * @param message the command message
     */
    public RssiRequestCommand(final ZclCommandMessage message) {
        super(message);
    }

    @Override
    public ZclCommandMessage toCommandMessage() {
        final ZclCommandMessage message = super.toCommandMessage();
        return message;
    }

    @Override
    public String toString() {
        final StringBuilder builder = new StringBuilder();
        builder.append(super.toString());
        return builder.toString();
    }

}
